In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
##Sentenced
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#define vocab size
voc_size = 10000

In [5]:
#one hot representation
one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[4568, 8260, 5167, 4078],
 [4568, 8260, 5167, 8182],
 [4568, 1075, 5167, 7031],
 [275, 2208, 3494, 5106, 9853],
 [275, 2208, 3494, 5106, 9000],
 [9086, 4568, 9665, 5167, 7542],
 [3589, 2336, 6409, 5106]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4568 8260 5167 4078]
 [   0    0    0    0 4568 8260 5167 8182]
 [   0    0    0    0 4568 1075 5167 7031]
 [   0    0    0  275 2208 3494 5106 9853]
 [   0    0    0  275 2208 3494 5106 9000]
 [   0    0    0 9086 4568 9665 5167 7542]
 [   0    0    0    0 3589 2336 6409 5106]]


In [9]:
#Feature Representation
dim=10

In [10]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 224ms/step


array([[[ 0.03187138,  0.03052027, -0.0046627 , -0.02436198,
          0.00339925, -0.04636786,  0.04399598,  0.02786234,
          0.0020191 , -0.00837187],
        [ 0.03187138,  0.03052027, -0.0046627 , -0.02436198,
          0.00339925, -0.04636786,  0.04399598,  0.02786234,
          0.0020191 , -0.00837187],
        [ 0.03187138,  0.03052027, -0.0046627 , -0.02436198,
          0.00339925, -0.04636786,  0.04399598,  0.02786234,
          0.0020191 , -0.00837187],
        [ 0.03187138,  0.03052027, -0.0046627 , -0.02436198,
          0.00339925, -0.04636786,  0.04399598,  0.02786234,
          0.0020191 , -0.00837187],
        [ 0.04052452, -0.04388887, -0.03130721,  0.04219088,
         -0.01239609,  0.00846654, -0.00590823, -0.0067613 ,
         -0.04284873,  0.04157234],
        [-0.0253745 ,  0.00875203,  0.0471634 ,  0.01357133,
         -0.04402203,  0.01049806, -0.00688127,  0.00730641,
          0.01319928,  0.04192736],
        [-0.04307003, -0.00078925,  0.0068556 ,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 4568, 8260, 5167, 4078])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 74ms/step


array([[ 0.03187138,  0.03052027, -0.0046627 , -0.02436198,  0.00339925,
        -0.04636786,  0.04399598,  0.02786234,  0.0020191 , -0.00837187],
       [ 0.03187138,  0.03052027, -0.0046627 , -0.02436198,  0.00339925,
        -0.04636786,  0.04399598,  0.02786234,  0.0020191 , -0.00837187],
       [ 0.03187138,  0.03052027, -0.0046627 , -0.02436198,  0.00339925,
        -0.04636786,  0.04399598,  0.02786234,  0.0020191 , -0.00837187],
       [ 0.03187138,  0.03052027, -0.0046627 , -0.02436198,  0.00339925,
        -0.04636786,  0.04399598,  0.02786234,  0.0020191 , -0.00837187],
       [ 0.04052452, -0.04388887, -0.03130721,  0.04219088, -0.01239609,
         0.00846654, -0.00590823, -0.0067613 , -0.04284873,  0.04157234],
       [-0.0253745 ,  0.00875203,  0.0471634 ,  0.01357133, -0.04402203,
         0.01049806, -0.00688127,  0.00730641,  0.01319928,  0.04192736],
       [-0.04307003, -0.00078925,  0.0068556 ,  0.03913483, -0.01300032,
         0.03868467, -0.01414027, -0.03085343